language: go

# github.com/flynn/hid is broken on go1.9.4 on MacOS X, so pin to go1.9.3
go:
    - 1.9.3

os:
    - linux
    - osx

before_install:
    - REPO_NAME=$(basename $PWD)
    - GITHUB_PATH=$(dirname $(dirname $PWD))
    - SYMANTEC_PROJECT_DIR=${GITHUB_PATH}/Symantec/${REPO_NAME}
    - mkdir -p ${SYMANTEC_PROJECT_DIR}
    - rsync -az ${TRAVIS_BUILD_DIR}/ ${SYMANTEC_PROJECT_DIR}/
    - export TRAVIS_BUILD_DIR=${SYMANTEC_PROJECT_DIR}
    - cd ${SYMANTEC_PROJECT_DIR}

install: make get-deps

script: make all test
